#!/bin/sh
#

[ -r /etc/lsb-release ] && . /etc/lsb-release

printf "\n"
echo "\e[1;34m 
                                                                 
                                         
                    ======+++++++++*             
                   =======+++++++++              
                 :-=======++++++++               
                :--==+++-::::::. ::::::::        
               =#######.         .--------       
            .********.            --------      
           .********               --------     
            .********               --------     
             .********.            --------      
               =#######.         .--------       
                :--==+++-::::::. ::::::::        
                 :-=======++++++++               
                   =======+++++++++              
                    ======+++++++++*             
                                        
  _       _                                   ____   _   _   _   _ 
 | |     (_)  _ __    _   _  __  __          / ___| | \ | | | | | |
 | |     | | | '_ \  | | | | \ \/ /         | |  _  |  \| | | | | |
 | |___  | | | | | | | |_| |  >  <          | |_| | | |\  | | |_| |
 |_____| |_| |_| |_|  \__,_| /_/\_\  _____   \____| |_| \_|  \___/ 
                                    |_____|                        
                                             
                                      
\e[0m"

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
printf "\n"
printf "Welcome to %s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"

      
                                        
                                        
  
                                  